# Generated by Django 2.2.5 on 2019-09-23 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.AddField(
            model_name='product',
            name='provide_by',
            field=models.CharField(default='King Pro Pvt Ltd', max_length=120),
        ),
    ]
