# Generated by Django 2.2.5 on 2019-10-01 15:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20191001_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 1, 15, 22, 9, 846086, tzinfo=utc)),
        ),
    ]
