# Generated by Django 2.2.5 on 2019-10-03 16:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_auto_20191003_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='studied_from',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 3, 22, 27, 55, 402308)),
        ),
        migrations.AlterField(
            model_name='education',
            name='studied_until',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 3, 22, 27, 55, 402308)),
        ),
        migrations.AlterField(
            model_name='experience',
            name='worked_from',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 3, 22, 27, 55, 401308)),
        ),
        migrations.AlterField(
            model_name='experience',
            name='worked_until',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 3, 22, 27, 55, 401308)),
        ),
    ]
