# Generated by Django 2.2.5 on 2019-10-03 17:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0015_auto_20191003_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='studied_from',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 10, 3, 22, 31, 0, 253880), null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='studied_until',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 10, 3, 22, 31, 0, 253880), null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='worked_from',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 10, 3, 22, 31, 0, 253880), null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='worked_until',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 10, 3, 22, 31, 0, 253880), null=True),
        ),
    ]
