# Generated by Django 2.2.5 on 2019-10-05 12:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0017_auto_20191003_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='currently_studying',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.CharField(default='BSC', max_length=100),
        ),
        migrations.AlterField(
            model_name='education',
            name='field_of_study',
            field=models.CharField(default='Computer Science', max_length=150),
        ),
        migrations.AlterField(
            model_name='education',
            name='school',
            field=models.CharField(default='New Collage', max_length=120),
        ),
        migrations.AlterField(
            model_name='education',
            name='studied_from',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='education',
            name='studied_until',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='experience',
            name='company',
            field=models.CharField(default='New Company Pvt Ltd', max_length=120),
        ),
        migrations.AlterField(
            model_name='experience',
            name='currently_work_here',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='experience',
            name='location',
            field=models.CharField(default='Sri Lanka', max_length=100),
        ),
        migrations.AlterField(
            model_name='experience',
            name='worked_from',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='experience',
            name='worked_until',
            field=models.DateField(),
        ),
    ]
