# Generated by Django 2.2.5 on 2019-10-05 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0018_auto_20191005_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='company',
            field=models.CharField(default='Some Company Pvt Ltd', max_length=150),
        ),
    ]
