# Generated by Django 2.1.7 on 2019-10-09 18:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0019_auto_20191005_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='studied_from',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='education',
            name='studied_until',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='experience',
            name='worked_from',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='experience',
            name='worked_until',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='profile',
            name='skills',
            field=models.TextField(blank=True, default='Marketing Programming', null=True),
        ),
    ]
